apiVersion: "config.istio.io/v1alpha2"
kind: svcctrl
metadata:
  name: testhandler
  namespace: istio-system
spec:
  runtime_config:
    check_cache_size: 200
    check_result_expiration: 60s
  credential_path: "/etc/token/token.json"
  service_configs:
    - mesh_service_name: "echo.default.svc.cluster.local"
      google_service_name: "simple-echo.endpoints.istio-manlinl.cloud.goog"
      quotas:
        - name: ratelimit.quota.istio-system
          google_quota_metric_name: read-requests
          expiration: 1m
---
apiVersion: "config.istio.io/v1alpha2"
kind: apikey
metadata:
  name: check
  namespace: istio-system
spec:
  api: api.service | ""
  api_version: '"v1"'
  api_operation : api.operation
  api_key : request.api_key
  timestamp : request.time
---
apiVersion: "config.istio.io/v1alpha2"
kind: svcctrlreport
metadata:
  name: report
  namespace: istio-system
spec:
  api_version : '"v1"'
  api_operation : api.operation | ""
  api_protocol : api.protocol | ""
  api_service : api.service | ""
  api_key : request.api_key | ""
  request_time : request.time
  request_method : request.method
  request_path : request.path
  request_bytes: request.size
  response_time : response.time
  response_code : response.code | 520
  response_bytes : response.size | 0
  response_latency : response.duration | "0ms"
---
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: ratelimit
  namespace: istio-system
spec:
  dimensions:
    api_operation : api.operation
    api_key : request.api_key
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: svcctrl-rule
  namespace: istio-system
spec:
  match: destination.service == "echo.default.svc.cluster.local"
  actions:
  - handler: testhandler.svcctrl
    instances:
    - check.apikey
    - report.svcctrlreport
    - ratelimit.quota
