apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpec
metadata:
  creationTimestamp: null
  name: echo
  namespace: default
spec:
  apiKeys:
  - query: key
  attributes:
    attributes:
      api.service:
        stringValue: simple-echo.endpoints.istio-manlinl.cloud.goog
      api.version:
        stringValue: 1.0.0
  patterns:
  - attributes:
      attributes:
        api.operation:
          stringValue: echo
    httpMethod: POST
    uriTemplate: /echo
---
apiVersion: config.istio.io/v1alpha2
kind: HTTPAPISpecBinding
metadata:
  creationTimestamp: null
  name: echo
  namespace: default
spec:
  apiSpecs:
  - name: echo
    namespace: default
  services:
  - name: echo
    namespace: default
